ALTER TABLE "users_sessions" ADD CONSTRAINT "users_sessions_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "authors" ADD CONSTRAINT "authors_avatar_id_media_id_fk" FOREIGN KEY ("avatar_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "testimonials" ADD CONSTRAINT "testimonials_avatar_id_media_id_fk" FOREIGN KEY ("avatar_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "blog_posts" ADD CONSTRAINT "blog_posts_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "blog_posts" ADD CONSTRAINT "blog_posts_featured_image_id_media_id_fk" FOREIGN KEY ("featured_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "blog_posts" ADD CONSTRAINT "blog_posts_author_id_authors_id_fk" FOREIGN KEY ("author_id") REFERENCES "public"."authors"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "blog_posts" ADD CONSTRAINT "blog_posts_meta_image_id_media_id_fk" FOREIGN KEY ("meta_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "blog_posts_rels" ADD CONSTRAINT "blog_posts_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."blog_posts"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "blog_posts_rels" ADD CONSTRAINT "blog_posts_rels_tags_fk" FOREIGN KEY ("tags_id") REFERENCES "public"."tags"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_blog_posts_v" ADD CONSTRAINT "_blog_posts_v_parent_id_blog_posts_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."blog_posts"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "_blog_posts_v" ADD CONSTRAINT "_blog_posts_v_version_category_id_categories_id_fk" FOREIGN KEY ("version_category_id") REFERENCES "public"."categories"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "_blog_posts_v" ADD CONSTRAINT "_blog_posts_v_version_featured_image_id_media_id_fk" FOREIGN KEY ("version_featured_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "_blog_posts_v" ADD CONSTRAINT "_blog_posts_v_version_author_id_authors_id_fk" FOREIGN KEY ("version_author_id") REFERENCES "public"."authors"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "_blog_posts_v" ADD CONSTRAINT "_blog_posts_v_version_meta_image_id_media_id_fk" FOREIGN KEY ("version_meta_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "_blog_posts_v_rels" ADD CONSTRAINT "_blog_posts_v_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."_blog_posts_v"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_blog_posts_v_rels" ADD CONSTRAINT "_blog_posts_v_rels_tags_fk" FOREIGN KEY ("tags_id") REFERENCES "public"."tags"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "case_studies" ADD CONSTRAINT "case_studies_category_id_categories_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."categories"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "case_studies" ADD CONSTRAINT "case_studies_related_service_id_services_id_fk" FOREIGN KEY ("related_service_id") REFERENCES "public"."services"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "case_studies" ADD CONSTRAINT "case_studies_featured_image_id_media_id_fk" FOREIGN KEY ("featured_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "case_studies" ADD CONSTRAINT "case_studies_testimonial_id_testimonials_id_fk" FOREIGN KEY ("testimonial_id") REFERENCES "public"."testimonials"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "case_studies" ADD CONSTRAINT "case_studies_meta_image_id_media_id_fk" FOREIGN KEY ("meta_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "case_studies_rels" ADD CONSTRAINT "case_studies_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."case_studies"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "case_studies_rels" ADD CONSTRAINT "case_studies_rels_tags_fk" FOREIGN KEY ("tags_id") REFERENCES "public"."tags"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_case_studies_v" ADD CONSTRAINT "_case_studies_v_parent_id_case_studies_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."case_studies"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "_case_studies_v" ADD CONSTRAINT "_case_studies_v_version_category_id_categories_id_fk" FOREIGN KEY ("version_category_id") REFERENCES "public"."categories"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "_case_studies_v" ADD CONSTRAINT "_case_studies_v_version_related_service_id_services_id_fk" FOREIGN KEY ("version_related_service_id") REFERENCES "public"."services"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "_case_studies_v" ADD CONSTRAINT "_case_studies_v_version_featured_image_id_media_id_fk" FOREIGN KEY ("version_featured_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "_case_studies_v" ADD CONSTRAINT "_case_studies_v_version_testimonial_id_testimonials_id_fk" FOREIGN KEY ("version_testimonial_id") REFERENCES "public"."testimonials"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "_case_studies_v" ADD CONSTRAINT "_case_studies_v_version_meta_image_id_media_id_fk" FOREIGN KEY ("version_meta_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "_case_studies_v_rels" ADD CONSTRAINT "_case_studies_v_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."_case_studies_v"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_case_studies_v_rels" ADD CONSTRAINT "_case_studies_v_rels_tags_fk" FOREIGN KEY ("tags_id") REFERENCES "public"."tags"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "tags_applies_to" ADD CONSTRAINT "tags_applies_to_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."tags"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "services_hero_links" ADD CONSTRAINT "services_hero_links_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."services"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "services_hero_trust_indicators" ADD CONSTRAINT "services_hero_trust_indicators_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."services"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "services_process" ADD CONSTRAINT "services_process_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."services"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "services_faqs" ADD CONSTRAINT "services_faqs_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."services"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "services" ADD CONSTRAINT "services_hero_bg_image_id_media_id_fk" FOREIGN KEY ("hero_bg_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "services" ADD CONSTRAINT "services_hero_fg_image_id_media_id_fk" FOREIGN KEY ("hero_fg_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "services" ADD CONSTRAINT "services_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "services" ADD CONSTRAINT "services_parent_service_id_services_id_fk" FOREIGN KEY ("parent_service_id") REFERENCES "public"."services"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "services" ADD CONSTRAINT "services_meta_image_id_media_id_fk" FOREIGN KEY ("meta_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "services_rels" ADD CONSTRAINT "services_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."services"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "services_rels" ADD CONSTRAINT "services_rels_pages_fk" FOREIGN KEY ("pages_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "services_rels" ADD CONSTRAINT "services_rels_services_fk" FOREIGN KEY ("services_id") REFERENCES "public"."services"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "reviews" ADD CONSTRAINT "reviews_avatar_id_media_id_fk" FOREIGN KEY ("avatar_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "pages_blocks_legal_content" ADD CONSTRAINT "pages_blocks_legal_content_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "pages_blocks_legal_contact" ADD CONSTRAINT "pages_blocks_legal_contact_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "pages_blocks_back_link" ADD CONSTRAINT "pages_blocks_back_link_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "pages_blocks_faq" ADD CONSTRAINT "pages_blocks_faq_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "pages_blocks_reviews_section_manual_reviews" ADD CONSTRAINT "pages_blocks_reviews_section_manual_reviews_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_reviews_section"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "pages_blocks_reviews_section" ADD CONSTRAINT "pages_blocks_reviews_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "pages_blocks_certifications_certifications" ADD CONSTRAINT "pages_blocks_certifications_certifications_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_certifications"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "pages_blocks_certifications" ADD CONSTRAINT "pages_blocks_certifications_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "pages_blocks_team" ADD CONSTRAINT "pages_blocks_team_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "pages_blocks_trust_stats_stats" ADD CONSTRAINT "pages_blocks_trust_stats_stats_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_trust_stats"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "pages_blocks_trust_stats" ADD CONSTRAINT "pages_blocks_trust_stats_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "pages_blocks_timeline_items" ADD CONSTRAINT "pages_blocks_timeline_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages_blocks_timeline"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "pages_blocks_timeline" ADD CONSTRAINT "pages_blocks_timeline_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "pages_blocks_content_fetcher" ADD CONSTRAINT "pages_blocks_content_fetcher_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "pages_hero_links" ADD CONSTRAINT "pages_hero_links_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "pages_hero_trust_indicators" ADD CONSTRAINT "pages_hero_trust_indicators_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "pages" ADD CONSTRAINT "pages_hero_bg_image_id_media_id_fk" FOREIGN KEY ("hero_bg_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "pages" ADD CONSTRAINT "pages_hero_fg_image_id_media_id_fk" FOREIGN KEY ("hero_fg_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "pages" ADD CONSTRAINT "pages_meta_image_id_media_id_fk" FOREIGN KEY ("meta_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "pages_rels" ADD CONSTRAINT "pages_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "pages_rels" ADD CONSTRAINT "pages_rels_faqs_fk" FOREIGN KEY ("faqs_id") REFERENCES "public"."faqs"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "pages_rels" ADD CONSTRAINT "pages_rels_pages_fk" FOREIGN KEY ("pages_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "pages_rels" ADD CONSTRAINT "pages_rels_services_fk" FOREIGN KEY ("services_id") REFERENCES "public"."services"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "pages_rels" ADD CONSTRAINT "pages_rels_reviews_fk" FOREIGN KEY ("reviews_id") REFERENCES "public"."reviews"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "pages_rels" ADD CONSTRAINT "pages_rels_team_members_fk" FOREIGN KEY ("team_members_id") REFERENCES "public"."team_members"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v_blocks_legal_content" ADD CONSTRAINT "_pages_v_blocks_legal_content_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v_blocks_legal_contact" ADD CONSTRAINT "_pages_v_blocks_legal_contact_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v_blocks_back_link" ADD CONSTRAINT "_pages_v_blocks_back_link_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v_blocks_faq" ADD CONSTRAINT "_pages_v_blocks_faq_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v_blocks_reviews_section_manual_reviews" ADD CONSTRAINT "_pages_v_blocks_reviews_section_manual_reviews_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_reviews_section"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v_blocks_reviews_section" ADD CONSTRAINT "_pages_v_blocks_reviews_section_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v_blocks_certifications_certifications" ADD CONSTRAINT "_pages_v_blocks_certifications_certifications_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_certifications"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v_blocks_certifications" ADD CONSTRAINT "_pages_v_blocks_certifications_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v_blocks_team" ADD CONSTRAINT "_pages_v_blocks_team_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v_blocks_trust_stats_stats" ADD CONSTRAINT "_pages_v_blocks_trust_stats_stats_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_trust_stats"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v_blocks_trust_stats" ADD CONSTRAINT "_pages_v_blocks_trust_stats_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v_blocks_timeline_items" ADD CONSTRAINT "_pages_v_blocks_timeline_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v_blocks_timeline"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v_blocks_timeline" ADD CONSTRAINT "_pages_v_blocks_timeline_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v_blocks_content_fetcher" ADD CONSTRAINT "_pages_v_blocks_content_fetcher_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v_version_hero_links" ADD CONSTRAINT "_pages_v_version_hero_links_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v_version_hero_trust_indicators" ADD CONSTRAINT "_pages_v_version_hero_trust_indicators_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v" ADD CONSTRAINT "_pages_v_parent_id_pages_id_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."pages"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "_pages_v" ADD CONSTRAINT "_pages_v_version_hero_bg_image_id_media_id_fk" FOREIGN KEY ("version_hero_bg_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "_pages_v" ADD CONSTRAINT "_pages_v_version_hero_fg_image_id_media_id_fk" FOREIGN KEY ("version_hero_fg_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "_pages_v" ADD CONSTRAINT "_pages_v_version_meta_image_id_media_id_fk" FOREIGN KEY ("version_meta_image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "_pages_v_rels" ADD CONSTRAINT "_pages_v_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."_pages_v"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v_rels" ADD CONSTRAINT "_pages_v_rels_faqs_fk" FOREIGN KEY ("faqs_id") REFERENCES "public"."faqs"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v_rels" ADD CONSTRAINT "_pages_v_rels_pages_fk" FOREIGN KEY ("pages_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v_rels" ADD CONSTRAINT "_pages_v_rels_services_fk" FOREIGN KEY ("services_id") REFERENCES "public"."services"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v_rels" ADD CONSTRAINT "_pages_v_rels_reviews_fk" FOREIGN KEY ("reviews_id") REFERENCES "public"."reviews"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "_pages_v_rels" ADD CONSTRAINT "_pages_v_rels_team_members_fk" FOREIGN KEY ("team_members_id") REFERENCES "public"."team_members"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "team_members_certifications" ADD CONSTRAINT "team_members_certifications_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."team_members"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "team_members" ADD CONSTRAINT "team_members_image_id_media_id_fk" FOREIGN KEY ("image_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "categories_applies_to" ADD CONSTRAINT "categories_applies_to_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."categories"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."payload_locked_documents"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_users_fk" FOREIGN KEY ("users_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_media_fk" FOREIGN KEY ("media_id") REFERENCES "public"."media"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_authors_fk" FOREIGN KEY ("authors_id") REFERENCES "public"."authors"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_testimonials_fk" FOREIGN KEY ("testimonials_id") REFERENCES "public"."testimonials"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_blog_posts_fk" FOREIGN KEY ("blog_posts_id") REFERENCES "public"."blog_posts"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_case_studies_fk" FOREIGN KEY ("case_studies_id") REFERENCES "public"."case_studies"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_tags_fk" FOREIGN KEY ("tags_id") REFERENCES "public"."tags"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_services_fk" FOREIGN KEY ("services_id") REFERENCES "public"."services"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_reviews_fk" FOREIGN KEY ("reviews_id") REFERENCES "public"."reviews"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_pages_fk" FOREIGN KEY ("pages_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_faqs_fk" FOREIGN KEY ("faqs_id") REFERENCES "public"."faqs"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_team_members_fk" FOREIGN KEY ("team_members_id") REFERENCES "public"."team_members"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "payload_locked_documents_rels" ADD CONSTRAINT "payload_locked_documents_rels_categories_fk" FOREIGN KEY ("categories_id") REFERENCES "public"."categories"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "payload_preferences_rels" ADD CONSTRAINT "payload_preferences_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."payload_preferences"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "payload_preferences_rels" ADD CONSTRAINT "payload_preferences_rels_users_fk" FOREIGN KEY ("users_id") REFERENCES "public"."users"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "header_nav_items" ADD CONSTRAINT "header_nav_items_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."header"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "header_rels" ADD CONSTRAINT "header_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."header"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "header_rels" ADD CONSTRAINT "header_rels_pages_fk" FOREIGN KEY ("pages_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "header_rels" ADD CONSTRAINT "header_rels_services_fk" FOREIGN KEY ("services_id") REFERENCES "public"."services"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "footer_cta_links" ADD CONSTRAINT "footer_cta_links_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."footer"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "footer_nav_links" ADD CONSTRAINT "footer_nav_links_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."footer"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "footer_bottom_links" ADD CONSTRAINT "footer_bottom_links_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."footer"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "footer_rels" ADD CONSTRAINT "footer_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."footer"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "footer_rels" ADD CONSTRAINT "footer_rels_pages_fk" FOREIGN KEY ("pages_id") REFERENCES "public"."pages"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "footer_rels" ADD CONSTRAINT "footer_rels_services_fk" FOREIGN KEY ("services_id") REFERENCES "public"."services"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "company_info_socials" ADD CONSTRAINT "company_info_socials_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."company_info"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "company_info_working_hours" ADD CONSTRAINT "company_info_working_hours_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."company_info"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "company_info_seo_service_areas" ADD CONSTRAINT "company_info_seo_service_areas_parent_id_fk" FOREIGN KEY ("_parent_id") REFERENCES "public"."company_info"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "company_info" ADD CONSTRAINT "company_info_brand_logo_id_media_id_fk" FOREIGN KEY ("brand_logo_id") REFERENCES "public"."media"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "company_info" ADD CONSTRAINT "company_info_seo_emergency_service_id_services_id_fk" FOREIGN KEY ("seo_emergency_service_id") REFERENCES "public"."services"("id") ON DELETE set null ON UPDATE no action;
ALTER TABLE "company_info_rels" ADD CONSTRAINT "company_info_rels_parent_fk" FOREIGN KEY ("parent_id") REFERENCES "public"."company_info"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "company_info_rels" ADD CONSTRAINT "company_info_rels_services_fk" FOREIGN KEY ("services_id") REFERENCES "public"."services"("id") ON DELETE cascade ON UPDATE no action;
ALTER TABLE "company_info_rels" ADD CONSTRAINT "company_info_rels_reviews_fk" FOREIGN KEY ("reviews_id") REFERENCES "public"."reviews"("id") ON DELETE cascade ON UPDATE no action;
CREATE INDEX "users_sessions_order_idx" ON "users_sessions" USING btree ("_order");
CREATE INDEX "users_sessions_parent_id_idx" ON "users_sessions" USING btree ("_parent_id");
CREATE INDEX "users_updated_at_idx" ON "users" USING btree ("updated_at");
CREATE INDEX "users_created_at_idx" ON "users" USING btree ("created_at");
CREATE UNIQUE INDEX "users_email_idx" ON "users" USING btree ("email");
CREATE INDEX "media_updated_at_idx" ON "media" USING btree ("updated_at");
CREATE INDEX "media_created_at_idx" ON "media" USING btree ("created_at");
CREATE UNIQUE INDEX "media_filename_idx" ON "media" USING btree ("filename");
CREATE INDEX "media_sizes_thumbnail_sizes_thumbnail_filename_idx" ON "media" USING btree ("sizes_thumbnail_filename");
CREATE INDEX "media_sizes_card_sizes_card_filename_idx" ON "media" USING btree ("sizes_card_filename");
CREATE INDEX "media_sizes_tablet_sizes_tablet_filename_idx" ON "media" USING btree ("sizes_tablet_filename");
CREATE INDEX "authors_avatar_idx" ON "authors" USING btree ("avatar_id");
CREATE INDEX "authors_updated_at_idx" ON "authors" USING btree ("updated_at");
CREATE INDEX "authors_created_at_idx" ON "authors" USING btree ("created_at");
CREATE INDEX "testimonials_avatar_idx" ON "testimonials" USING btree ("avatar_id");
CREATE INDEX "testimonials_updated_at_idx" ON "testimonials" USING btree ("updated_at");
CREATE INDEX "testimonials_created_at_idx" ON "testimonials" USING btree ("created_at");
CREATE INDEX "blog_posts_category_idx" ON "blog_posts" USING btree ("category_id");
CREATE INDEX "blog_posts_featured_image_idx" ON "blog_posts" USING btree ("featured_image_id");
CREATE INDEX "blog_posts_author_idx" ON "blog_posts" USING btree ("author_id");
CREATE INDEX "blog_posts_meta_meta_image_idx" ON "blog_posts" USING btree ("meta_image_id");
CREATE INDEX "blog_posts_updated_at_idx" ON "blog_posts" USING btree ("updated_at");
CREATE INDEX "blog_posts_created_at_idx" ON "blog_posts" USING btree ("created_at");
CREATE INDEX "blog_posts__status_idx" ON "blog_posts" USING btree ("_status");
CREATE INDEX "blog_posts_rels_order_idx" ON "blog_posts_rels" USING btree ("order");
CREATE INDEX "blog_posts_rels_parent_idx" ON "blog_posts_rels" USING btree ("parent_id");
CREATE INDEX "blog_posts_rels_path_idx" ON "blog_posts_rels" USING btree ("path");
CREATE INDEX "blog_posts_rels_tags_id_idx" ON "blog_posts_rels" USING btree ("tags_id");
CREATE INDEX "_blog_posts_v_parent_idx" ON "_blog_posts_v" USING btree ("parent_id");
CREATE INDEX "_blog_posts_v_version_version_category_idx" ON "_blog_posts_v" USING btree ("version_category_id");
CREATE INDEX "_blog_posts_v_version_version_featured_image_idx" ON "_blog_posts_v" USING btree ("version_featured_image_id");
CREATE INDEX "_blog_posts_v_version_version_author_idx" ON "_blog_posts_v" USING btree ("version_author_id");
CREATE INDEX "_blog_posts_v_version_meta_version_meta_image_idx" ON "_blog_posts_v" USING btree ("version_meta_image_id");
CREATE INDEX "_blog_posts_v_version_version_updated_at_idx" ON "_blog_posts_v" USING btree ("version_updated_at");
CREATE INDEX "_blog_posts_v_version_version_created_at_idx" ON "_blog_posts_v" USING btree ("version_created_at");
CREATE INDEX "_blog_posts_v_version_version__status_idx" ON "_blog_posts_v" USING btree ("version__status");
CREATE INDEX "_blog_posts_v_created_at_idx" ON "_blog_posts_v" USING btree ("created_at");
CREATE INDEX "_blog_posts_v_updated_at_idx" ON "_blog_posts_v" USING btree ("updated_at");
CREATE INDEX "_blog_posts_v_latest_idx" ON "_blog_posts_v" USING btree ("latest");
CREATE INDEX "_blog_posts_v_rels_order_idx" ON "_blog_posts_v_rels" USING btree ("order");
CREATE INDEX "_blog_posts_v_rels_parent_idx" ON "_blog_posts_v_rels" USING btree ("parent_id");
CREATE INDEX "_blog_posts_v_rels_path_idx" ON "_blog_posts_v_rels" USING btree ("path");
CREATE INDEX "_blog_posts_v_rels_tags_id_idx" ON "_blog_posts_v_rels" USING btree ("tags_id");
CREATE INDEX "case_studies_category_idx" ON "case_studies" USING btree ("category_id");
CREATE INDEX "case_studies_related_service_idx" ON "case_studies" USING btree ("related_service_id");
CREATE INDEX "case_studies_featured_image_idx" ON "case_studies" USING btree ("featured_image_id");
CREATE INDEX "case_studies_testimonial_idx" ON "case_studies" USING btree ("testimonial_id");
CREATE INDEX "case_studies_meta_meta_image_idx" ON "case_studies" USING btree ("meta_image_id");
CREATE INDEX "case_studies_updated_at_idx" ON "case_studies" USING btree ("updated_at");
CREATE INDEX "case_studies_created_at_idx" ON "case_studies" USING btree ("created_at");
CREATE INDEX "case_studies__status_idx" ON "case_studies" USING btree ("_status");
CREATE INDEX "case_studies_rels_order_idx" ON "case_studies_rels" USING btree ("order");
CREATE INDEX "case_studies_rels_parent_idx" ON "case_studies_rels" USING btree ("parent_id");
CREATE INDEX "case_studies_rels_path_idx" ON "case_studies_rels" USING btree ("path");
CREATE INDEX "case_studies_rels_tags_id_idx" ON "case_studies_rels" USING btree ("tags_id");
CREATE INDEX "_case_studies_v_parent_idx" ON "_case_studies_v" USING btree ("parent_id");
CREATE INDEX "_case_studies_v_version_version_category_idx" ON "_case_studies_v" USING btree ("version_category_id");
CREATE INDEX "_case_studies_v_version_version_related_service_idx" ON "_case_studies_v" USING btree ("version_related_service_id");
CREATE INDEX "_case_studies_v_version_version_featured_image_idx" ON "_case_studies_v" USING btree ("version_featured_image_id");
CREATE INDEX "_case_studies_v_version_version_testimonial_idx" ON "_case_studies_v" USING btree ("version_testimonial_id");
CREATE INDEX "_case_studies_v_version_meta_version_meta_image_idx" ON "_case_studies_v" USING btree ("version_meta_image_id");
CREATE INDEX "_case_studies_v_version_version_updated_at_idx" ON "_case_studies_v" USING btree ("version_updated_at");
CREATE INDEX "_case_studies_v_version_version_created_at_idx" ON "_case_studies_v" USING btree ("version_created_at");
CREATE INDEX "_case_studies_v_version_version__status_idx" ON "_case_studies_v" USING btree ("version__status");
CREATE INDEX "_case_studies_v_created_at_idx" ON "_case_studies_v" USING btree ("created_at");
CREATE INDEX "_case_studies_v_updated_at_idx" ON "_case_studies_v" USING btree ("updated_at");
CREATE INDEX "_case_studies_v_latest_idx" ON "_case_studies_v" USING btree ("latest");
CREATE INDEX "_case_studies_v_rels_order_idx" ON "_case_studies_v_rels" USING btree ("order");
CREATE INDEX "_case_studies_v_rels_parent_idx" ON "_case_studies_v_rels" USING btree ("parent_id");
CREATE INDEX "_case_studies_v_rels_path_idx" ON "_case_studies_v_rels" USING btree ("path");
CREATE INDEX "_case_studies_v_rels_tags_id_idx" ON "_case_studies_v_rels" USING btree ("tags_id");
CREATE INDEX "tags_applies_to_order_idx" ON "tags_applies_to" USING btree ("order");
CREATE INDEX "tags_applies_to_parent_idx" ON "tags_applies_to" USING btree ("parent_id");
CREATE UNIQUE INDEX "tags_slug_idx" ON "tags" USING btree ("slug");
CREATE INDEX "tags_updated_at_idx" ON "tags" USING btree ("updated_at");
CREATE INDEX "tags_created_at_idx" ON "tags" USING btree ("created_at");
CREATE INDEX "services_hero_links_order_idx" ON "services_hero_links" USING btree ("_order");
CREATE INDEX "services_hero_links_parent_id_idx" ON "services_hero_links" USING btree ("_parent_id");
CREATE INDEX "services_hero_trust_indicators_order_idx" ON "services_hero_trust_indicators" USING btree ("_order");
CREATE INDEX "services_hero_trust_indicators_parent_id_idx" ON "services_hero_trust_indicators" USING btree ("_parent_id");
CREATE INDEX "services_process_order_idx" ON "services_process" USING btree ("_order");
CREATE INDEX "services_process_parent_id_idx" ON "services_process" USING btree ("_parent_id");
CREATE INDEX "services_faqs_order_idx" ON "services_faqs" USING btree ("_order");
CREATE INDEX "services_faqs_parent_id_idx" ON "services_faqs" USING btree ("_parent_id");
CREATE INDEX "services_hero_hero_bg_image_idx" ON "services" USING btree ("hero_bg_image_id");
CREATE INDEX "services_hero_hero_fg_image_idx" ON "services" USING btree ("hero_fg_image_id");
CREATE UNIQUE INDEX "services_slug_idx" ON "services" USING btree ("slug");
CREATE INDEX "services_image_idx" ON "services" USING btree ("image_id");
CREATE INDEX "services_parent_service_idx" ON "services" USING btree ("parent_service_id");
CREATE INDEX "services_meta_meta_image_idx" ON "services" USING btree ("meta_image_id");
CREATE INDEX "services_updated_at_idx" ON "services" USING btree ("updated_at");
CREATE INDEX "services_created_at_idx" ON "services" USING btree ("created_at");
CREATE INDEX "services_rels_order_idx" ON "services_rels" USING btree ("order");
CREATE INDEX "services_rels_parent_idx" ON "services_rels" USING btree ("parent_id");
CREATE INDEX "services_rels_path_idx" ON "services_rels" USING btree ("path");
CREATE INDEX "services_rels_pages_id_idx" ON "services_rels" USING btree ("pages_id");
CREATE INDEX "services_rels_services_id_idx" ON "services_rels" USING btree ("services_id");
CREATE INDEX "reviews_avatar_idx" ON "reviews" USING btree ("avatar_id");
CREATE INDEX "reviews_updated_at_idx" ON "reviews" USING btree ("updated_at");
CREATE INDEX "reviews_created_at_idx" ON "reviews" USING btree ("created_at");
CREATE INDEX "pages_blocks_legal_content_order_idx" ON "pages_blocks_legal_content" USING btree ("_order");
CREATE INDEX "pages_blocks_legal_content_parent_id_idx" ON "pages_blocks_legal_content" USING btree ("_parent_id");
CREATE INDEX "pages_blocks_legal_content_path_idx" ON "pages_blocks_legal_content" USING btree ("_path");
CREATE INDEX "pages_blocks_legal_contact_order_idx" ON "pages_blocks_legal_contact" USING btree ("_order");
CREATE INDEX "pages_blocks_legal_contact_parent_id_idx" ON "pages_blocks_legal_contact" USING btree ("_parent_id");
CREATE INDEX "pages_blocks_legal_contact_path_idx" ON "pages_blocks_legal_contact" USING btree ("_path");
CREATE INDEX "pages_blocks_back_link_order_idx" ON "pages_blocks_back_link" USING btree ("_order");
CREATE INDEX "pages_blocks_back_link_parent_id_idx" ON "pages_blocks_back_link" USING btree ("_parent_id");
CREATE INDEX "pages_blocks_back_link_path_idx" ON "pages_blocks_back_link" USING btree ("_path");
CREATE INDEX "pages_blocks_faq_order_idx" ON "pages_blocks_faq" USING btree ("_order");
CREATE INDEX "pages_blocks_faq_parent_id_idx" ON "pages_blocks_faq" USING btree ("_parent_id");
CREATE INDEX "pages_blocks_faq_path_idx" ON "pages_blocks_faq" USING btree ("_path");
CREATE INDEX "pages_blocks_reviews_section_manual_reviews_order_idx" ON "pages_blocks_reviews_section_manual_reviews" USING btree ("_order");
CREATE INDEX "pages_blocks_reviews_section_manual_reviews_parent_id_idx" ON "pages_blocks_reviews_section_manual_reviews" USING btree ("_parent_id");
CREATE INDEX "pages_blocks_reviews_section_order_idx" ON "pages_blocks_reviews_section" USING btree ("_order");
CREATE INDEX "pages_blocks_reviews_section_parent_id_idx" ON "pages_blocks_reviews_section" USING btree ("_parent_id");
CREATE INDEX "pages_blocks_reviews_section_path_idx" ON "pages_blocks_reviews_section" USING btree ("_path");
CREATE INDEX "pages_blocks_certifications_certifications_order_idx" ON "pages_blocks_certifications_certifications" USING btree ("_order");
CREATE INDEX "pages_blocks_certifications_certifications_parent_id_idx" ON "pages_blocks_certifications_certifications" USING btree ("_parent_id");
CREATE INDEX "pages_blocks_certifications_order_idx" ON "pages_blocks_certifications" USING btree ("_order");
CREATE INDEX "pages_blocks_certifications_parent_id_idx" ON "pages_blocks_certifications" USING btree ("_parent_id");
CREATE INDEX "pages_blocks_certifications_path_idx" ON "pages_blocks_certifications" USING btree ("_path");
CREATE INDEX "pages_blocks_team_order_idx" ON "pages_blocks_team" USING btree ("_order");
CREATE INDEX "pages_blocks_team_parent_id_idx" ON "pages_blocks_team" USING btree ("_parent_id");
CREATE INDEX "pages_blocks_team_path_idx" ON "pages_blocks_team" USING btree ("_path");
CREATE INDEX "pages_blocks_trust_stats_stats_order_idx" ON "pages_blocks_trust_stats_stats" USING btree ("_order");
CREATE INDEX "pages_blocks_trust_stats_stats_parent_id_idx" ON "pages_blocks_trust_stats_stats" USING btree ("_parent_id");
CREATE INDEX "pages_blocks_trust_stats_order_idx" ON "pages_blocks_trust_stats" USING btree ("_order");
CREATE INDEX "pages_blocks_trust_stats_parent_id_idx" ON "pages_blocks_trust_stats" USING btree ("_parent_id");
CREATE INDEX "pages_blocks_trust_stats_path_idx" ON "pages_blocks_trust_stats" USING btree ("_path");
CREATE INDEX "pages_blocks_timeline_items_order_idx" ON "pages_blocks_timeline_items" USING btree ("_order");
CREATE INDEX "pages_blocks_timeline_items_parent_id_idx" ON "pages_blocks_timeline_items" USING btree ("_parent_id");
CREATE INDEX "pages_blocks_timeline_order_idx" ON "pages_blocks_timeline" USING btree ("_order");
CREATE INDEX "pages_blocks_timeline_parent_id_idx" ON "pages_blocks_timeline" USING btree ("_parent_id");
CREATE INDEX "pages_blocks_timeline_path_idx" ON "pages_blocks_timeline" USING btree ("_path");
CREATE INDEX "pages_blocks_content_fetcher_order_idx" ON "pages_blocks_content_fetcher" USING btree ("_order");
CREATE INDEX "pages_blocks_content_fetcher_parent_id_idx" ON "pages_blocks_content_fetcher" USING btree ("_parent_id");
CREATE INDEX "pages_blocks_content_fetcher_path_idx" ON "pages_blocks_content_fetcher" USING btree ("_path");
CREATE INDEX "pages_hero_links_order_idx" ON "pages_hero_links" USING btree ("_order");
CREATE INDEX "pages_hero_links_parent_id_idx" ON "pages_hero_links" USING btree ("_parent_id");
CREATE INDEX "pages_hero_trust_indicators_order_idx" ON "pages_hero_trust_indicators" USING btree ("_order");
CREATE INDEX "pages_hero_trust_indicators_parent_id_idx" ON "pages_hero_trust_indicators" USING btree ("_parent_id");
CREATE UNIQUE INDEX "pages_slug_idx" ON "pages" USING btree ("slug");
CREATE INDEX "pages_hero_hero_bg_image_idx" ON "pages" USING btree ("hero_bg_image_id");
CREATE INDEX "pages_hero_hero_fg_image_idx" ON "pages" USING btree ("hero_fg_image_id");
CREATE INDEX "pages_meta_meta_image_idx" ON "pages" USING btree ("meta_image_id");
CREATE INDEX "pages_updated_at_idx" ON "pages" USING btree ("updated_at");
CREATE INDEX "pages_created_at_idx" ON "pages" USING btree ("created_at");
CREATE INDEX "pages__status_idx" ON "pages" USING btree ("_status");
CREATE INDEX "pages_rels_order_idx" ON "pages_rels" USING btree ("order");
CREATE INDEX "pages_rels_parent_idx" ON "pages_rels" USING btree ("parent_id");
CREATE INDEX "pages_rels_path_idx" ON "pages_rels" USING btree ("path");
CREATE INDEX "pages_rels_faqs_id_idx" ON "pages_rels" USING btree ("faqs_id");
CREATE INDEX "pages_rels_pages_id_idx" ON "pages_rels" USING btree ("pages_id");
CREATE INDEX "pages_rels_services_id_idx" ON "pages_rels" USING btree ("services_id");
CREATE INDEX "pages_rels_reviews_id_idx" ON "pages_rels" USING btree ("reviews_id");
CREATE INDEX "pages_rels_team_members_id_idx" ON "pages_rels" USING btree ("team_members_id");
CREATE INDEX "_pages_v_blocks_legal_content_order_idx" ON "_pages_v_blocks_legal_content" USING btree ("_order");
CREATE INDEX "_pages_v_blocks_legal_content_parent_id_idx" ON "_pages_v_blocks_legal_content" USING btree ("_parent_id");
CREATE INDEX "_pages_v_blocks_legal_content_path_idx" ON "_pages_v_blocks_legal_content" USING btree ("_path");
CREATE INDEX "_pages_v_blocks_legal_contact_order_idx" ON "_pages_v_blocks_legal_contact" USING btree ("_order");
CREATE INDEX "_pages_v_blocks_legal_contact_parent_id_idx" ON "_pages_v_blocks_legal_contact" USING btree ("_parent_id");
CREATE INDEX "_pages_v_blocks_legal_contact_path_idx" ON "_pages_v_blocks_legal_contact" USING btree ("_path");
CREATE INDEX "_pages_v_blocks_back_link_order_idx" ON "_pages_v_blocks_back_link" USING btree ("_order");
CREATE INDEX "_pages_v_blocks_back_link_parent_id_idx" ON "_pages_v_blocks_back_link" USING btree ("_parent_id");
CREATE INDEX "_pages_v_blocks_back_link_path_idx" ON "_pages_v_blocks_back_link" USING btree ("_path");
CREATE INDEX "_pages_v_blocks_faq_order_idx" ON "_pages_v_blocks_faq" USING btree ("_order");
CREATE INDEX "_pages_v_blocks_faq_parent_id_idx" ON "_pages_v_blocks_faq" USING btree ("_parent_id");
CREATE INDEX "_pages_v_blocks_faq_path_idx" ON "_pages_v_blocks_faq" USING btree ("_path");
CREATE INDEX "_pages_v_blocks_reviews_section_manual_reviews_order_idx" ON "_pages_v_blocks_reviews_section_manual_reviews" USING btree ("_order");
CREATE INDEX "_pages_v_blocks_reviews_section_manual_reviews_parent_id_idx" ON "_pages_v_blocks_reviews_section_manual_reviews" USING btree ("_parent_id");
CREATE INDEX "_pages_v_blocks_reviews_section_order_idx" ON "_pages_v_blocks_reviews_section" USING btree ("_order");
CREATE INDEX "_pages_v_blocks_reviews_section_parent_id_idx" ON "_pages_v_blocks_reviews_section" USING btree ("_parent_id");
CREATE INDEX "_pages_v_blocks_reviews_section_path_idx" ON "_pages_v_blocks_reviews_section" USING btree ("_path");
CREATE INDEX "_pages_v_blocks_certifications_certifications_order_idx" ON "_pages_v_blocks_certifications_certifications" USING btree ("_order");
CREATE INDEX "_pages_v_blocks_certifications_certifications_parent_id_idx" ON "_pages_v_blocks_certifications_certifications" USING btree ("_parent_id");
CREATE INDEX "_pages_v_blocks_certifications_order_idx" ON "_pages_v_blocks_certifications" USING btree ("_order");
CREATE INDEX "_pages_v_blocks_certifications_parent_id_idx" ON "_pages_v_blocks_certifications" USING btree ("_parent_id");
CREATE INDEX "_pages_v_blocks_certifications_path_idx" ON "_pages_v_blocks_certifications" USING btree ("_path");
CREATE INDEX "_pages_v_blocks_team_order_idx" ON "_pages_v_blocks_team" USING btree ("_order");
CREATE INDEX "_pages_v_blocks_team_parent_id_idx" ON "_pages_v_blocks_team" USING btree ("_parent_id");
CREATE INDEX "_pages_v_blocks_team_path_idx" ON "_pages_v_blocks_team" USING btree ("_path");
CREATE INDEX "_pages_v_blocks_trust_stats_stats_order_idx" ON "_pages_v_blocks_trust_stats_stats" USING btree ("_order");
CREATE INDEX "_pages_v_blocks_trust_stats_stats_parent_id_idx" ON "_pages_v_blocks_trust_stats_stats" USING btree ("_parent_id");
CREATE INDEX "_pages_v_blocks_trust_stats_order_idx" ON "_pages_v_blocks_trust_stats" USING btree ("_order");
CREATE INDEX "_pages_v_blocks_trust_stats_parent_id_idx" ON "_pages_v_blocks_trust_stats" USING btree ("_parent_id");
CREATE INDEX "_pages_v_blocks_trust_stats_path_idx" ON "_pages_v_blocks_trust_stats" USING btree ("_path");
CREATE INDEX "_pages_v_blocks_timeline_items_order_idx" ON "_pages_v_blocks_timeline_items" USING btree ("_order");
CREATE INDEX "_pages_v_blocks_timeline_items_parent_id_idx" ON "_pages_v_blocks_timeline_items" USING btree ("_parent_id");
CREATE INDEX "_pages_v_blocks_timeline_order_idx" ON "_pages_v_blocks_timeline" USING btree ("_order");
CREATE INDEX "_pages_v_blocks_timeline_parent_id_idx" ON "_pages_v_blocks_timeline" USING btree ("_parent_id");
CREATE INDEX "_pages_v_blocks_timeline_path_idx" ON "_pages_v_blocks_timeline" USING btree ("_path");
CREATE INDEX "_pages_v_blocks_content_fetcher_order_idx" ON "_pages_v_blocks_content_fetcher" USING btree ("_order");
CREATE INDEX "_pages_v_blocks_content_fetcher_parent_id_idx" ON "_pages_v_blocks_content_fetcher" USING btree ("_parent_id");
CREATE INDEX "_pages_v_blocks_content_fetcher_path_idx" ON "_pages_v_blocks_content_fetcher" USING btree ("_path");
CREATE INDEX "_pages_v_version_hero_links_order_idx" ON "_pages_v_version_hero_links" USING btree ("_order");
CREATE INDEX "_pages_v_version_hero_links_parent_id_idx" ON "_pages_v_version_hero_links" USING btree ("_parent_id");
CREATE INDEX "_pages_v_version_hero_trust_indicators_order_idx" ON "_pages_v_version_hero_trust_indicators" USING btree ("_order");
CREATE INDEX "_pages_v_version_hero_trust_indicators_parent_id_idx" ON "_pages_v_version_hero_trust_indicators" USING btree ("_parent_id");
CREATE INDEX "_pages_v_parent_idx" ON "_pages_v" USING btree ("parent_id");
CREATE INDEX "_pages_v_version_version_slug_idx" ON "_pages_v" USING btree ("version_slug");
CREATE INDEX "_pages_v_version_hero_version_hero_bg_image_idx" ON "_pages_v" USING btree ("version_hero_bg_image_id");
CREATE INDEX "_pages_v_version_hero_version_hero_fg_image_idx" ON "_pages_v" USING btree ("version_hero_fg_image_id");
CREATE INDEX "_pages_v_version_meta_version_meta_image_idx" ON "_pages_v" USING btree ("version_meta_image_id");
CREATE INDEX "_pages_v_version_version_updated_at_idx" ON "_pages_v" USING btree ("version_updated_at");
CREATE INDEX "_pages_v_version_version_created_at_idx" ON "_pages_v" USING btree ("version_created_at");
CREATE INDEX "_pages_v_version_version__status_idx" ON "_pages_v" USING btree ("version__status");
CREATE INDEX "_pages_v_created_at_idx" ON "_pages_v" USING btree ("created_at");
CREATE INDEX "_pages_v_updated_at_idx" ON "_pages_v" USING btree ("updated_at");
CREATE INDEX "_pages_v_latest_idx" ON "_pages_v" USING btree ("latest");
CREATE INDEX "_pages_v_rels_order_idx" ON "_pages_v_rels" USING btree ("order");
CREATE INDEX "_pages_v_rels_parent_idx" ON "_pages_v_rels" USING btree ("parent_id");
CREATE INDEX "_pages_v_rels_path_idx" ON "_pages_v_rels" USING btree ("path");
CREATE INDEX "_pages_v_rels_faqs_id_idx" ON "_pages_v_rels" USING btree ("faqs_id");
CREATE INDEX "_pages_v_rels_pages_id_idx" ON "_pages_v_rels" USING btree ("pages_id");
CREATE INDEX "_pages_v_rels_services_id_idx" ON "_pages_v_rels" USING btree ("services_id");
CREATE INDEX "_pages_v_rels_reviews_id_idx" ON "_pages_v_rels" USING btree ("reviews_id");
CREATE INDEX "_pages_v_rels_team_members_id_idx" ON "_pages_v_rels" USING btree ("team_members_id");
CREATE INDEX "faqs_updated_at_idx" ON "faqs" USING btree ("updated_at");
CREATE INDEX "faqs_created_at_idx" ON "faqs" USING btree ("created_at");
CREATE INDEX "team_members_certifications_order_idx" ON "team_members_certifications" USING btree ("_order");
CREATE INDEX "team_members_certifications_parent_id_idx" ON "team_members_certifications" USING btree ("_parent_id");
CREATE INDEX "team_members_image_idx" ON "team_members" USING btree ("image_id");
CREATE INDEX "team_members_updated_at_idx" ON "team_members" USING btree ("updated_at");
CREATE INDEX "team_members_created_at_idx" ON "team_members" USING btree ("created_at");
CREATE INDEX "categories_applies_to_order_idx" ON "categories_applies_to" USING btree ("order");
CREATE INDEX "categories_applies_to_parent_idx" ON "categories_applies_to" USING btree ("parent_id");
CREATE UNIQUE INDEX "categories_slug_idx" ON "categories" USING btree ("slug");
CREATE INDEX "categories_updated_at_idx" ON "categories" USING btree ("updated_at");
CREATE INDEX "categories_created_at_idx" ON "categories" USING btree ("created_at");
CREATE UNIQUE INDEX "payload_kv_key_idx" ON "payload_kv" USING btree ("key");
CREATE INDEX "payload_locked_documents_global_slug_idx" ON "payload_locked_documents" USING btree ("global_slug");
CREATE INDEX "payload_locked_documents_updated_at_idx" ON "payload_locked_documents" USING btree ("updated_at");
CREATE INDEX "payload_locked_documents_created_at_idx" ON "payload_locked_documents" USING btree ("created_at");
CREATE INDEX "payload_locked_documents_rels_order_idx" ON "payload_locked_documents_rels" USING btree ("order");
CREATE INDEX "payload_locked_documents_rels_parent_idx" ON "payload_locked_documents_rels" USING btree ("parent_id");
CREATE INDEX "payload_locked_documents_rels_path_idx" ON "payload_locked_documents_rels" USING btree ("path");
CREATE INDEX "payload_locked_documents_rels_users_id_idx" ON "payload_locked_documents_rels" USING btree ("users_id");
CREATE INDEX "payload_locked_documents_rels_media_id_idx" ON "payload_locked_documents_rels" USING btree ("media_id");
CREATE INDEX "payload_locked_documents_rels_authors_id_idx" ON "payload_locked_documents_rels" USING btree ("authors_id");
CREATE INDEX "payload_locked_documents_rels_testimonials_id_idx" ON "payload_locked_documents_rels" USING btree ("testimonials_id");
CREATE INDEX "payload_locked_documents_rels_blog_posts_id_idx" ON "payload_locked_documents_rels" USING btree ("blog_posts_id");
CREATE INDEX "payload_locked_documents_rels_case_studies_id_idx" ON "payload_locked_documents_rels" USING btree ("case_studies_id");
CREATE INDEX "payload_locked_documents_rels_tags_id_idx" ON "payload_locked_documents_rels" USING btree ("tags_id");
CREATE INDEX "payload_locked_documents_rels_services_id_idx" ON "payload_locked_documents_rels" USING btree ("services_id");
CREATE INDEX "payload_locked_documents_rels_reviews_id_idx" ON "payload_locked_documents_rels" USING btree ("reviews_id");
CREATE INDEX "payload_locked_documents_rels_pages_id_idx" ON "payload_locked_documents_rels" USING btree ("pages_id");
CREATE INDEX "payload_locked_documents_rels_faqs_id_idx" ON "payload_locked_documents_rels" USING btree ("faqs_id");
CREATE INDEX "payload_locked_documents_rels_team_members_id_idx" ON "payload_locked_documents_rels" USING btree ("team_members_id");
CREATE INDEX "payload_locked_documents_rels_categories_id_idx" ON "payload_locked_documents_rels" USING btree ("categories_id");
CREATE INDEX "payload_preferences_key_idx" ON "payload_preferences" USING btree ("key");
CREATE INDEX "payload_preferences_updated_at_idx" ON "payload_preferences" USING btree ("updated_at");
CREATE INDEX "payload_preferences_created_at_idx" ON "payload_preferences" USING btree ("created_at");
CREATE INDEX "payload_preferences_rels_order_idx" ON "payload_preferences_rels" USING btree ("order");
CREATE INDEX "payload_preferences_rels_parent_idx" ON "payload_preferences_rels" USING btree ("parent_id");
CREATE INDEX "payload_preferences_rels_path_idx" ON "payload_preferences_rels" USING btree ("path");
CREATE INDEX "payload_preferences_rels_users_id_idx" ON "payload_preferences_rels" USING btree ("users_id");
CREATE INDEX "payload_migrations_updated_at_idx" ON "payload_migrations" USING btree ("updated_at");
CREATE INDEX "payload_migrations_created_at_idx" ON "payload_migrations" USING btree ("created_at");
CREATE INDEX "header_nav_items_order_idx" ON "header_nav_items" USING btree ("_order");
CREATE INDEX "header_nav_items_parent_id_idx" ON "header_nav_items" USING btree ("_parent_id");
CREATE INDEX "header_rels_order_idx" ON "header_rels" USING btree ("order");
CREATE INDEX "header_rels_parent_idx" ON "header_rels" USING btree ("parent_id");
CREATE INDEX "header_rels_path_idx" ON "header_rels" USING btree ("path");
CREATE INDEX "header_rels_pages_id_idx" ON "header_rels" USING btree ("pages_id");
CREATE INDEX "header_rels_services_id_idx" ON "header_rels" USING btree ("services_id");
CREATE INDEX "footer_cta_links_order_idx" ON "footer_cta_links" USING btree ("_order");
CREATE INDEX "footer_cta_links_parent_id_idx" ON "footer_cta_links" USING btree ("_parent_id");
CREATE INDEX "footer_nav_links_order_idx" ON "footer_nav_links" USING btree ("_order");
CREATE INDEX "footer_nav_links_parent_id_idx" ON "footer_nav_links" USING btree ("_parent_id");
CREATE INDEX "footer_bottom_links_order_idx" ON "footer_bottom_links" USING btree ("_order");
CREATE INDEX "footer_bottom_links_parent_id_idx" ON "footer_bottom_links" USING btree ("_parent_id");
CREATE INDEX "footer_rels_order_idx" ON "footer_rels" USING btree ("order");
CREATE INDEX "footer_rels_parent_idx" ON "footer_rels" USING btree ("parent_id");
CREATE INDEX "footer_rels_path_idx" ON "footer_rels" USING btree ("path");
CREATE INDEX "footer_rels_pages_id_idx" ON "footer_rels" USING btree ("pages_id");
CREATE INDEX "footer_rels_services_id_idx" ON "footer_rels" USING btree ("services_id");
CREATE INDEX "company_info_socials_order_idx" ON "company_info_socials" USING btree ("_order");
CREATE INDEX "company_info_socials_parent_id_idx" ON "company_info_socials" USING btree ("_parent_id");
CREATE INDEX "company_info_working_hours_order_idx" ON "company_info_working_hours" USING btree ("_order");
CREATE INDEX "company_info_working_hours_parent_id_idx" ON "company_info_working_hours" USING btree ("_parent_id");
CREATE INDEX "company_info_seo_service_areas_order_idx" ON "company_info_seo_service_areas" USING btree ("_order");
CREATE INDEX "company_info_seo_service_areas_parent_id_idx" ON "company_info_seo_service_areas" USING btree ("_parent_id");
CREATE INDEX "company_info_brand_brand_logo_idx" ON "company_info" USING btree ("brand_logo_id");
CREATE INDEX "company_info_seo_seo_emergency_service_idx" ON "company_info" USING btree ("seo_emergency_service_id");
CREATE INDEX "company_info_rels_order_idx" ON "company_info_rels" USING btree ("order");
CREATE INDEX "company_info_rels_parent_idx" ON "company_info_rels" USING btree ("parent_id");
CREATE INDEX "company_info_rels_path_idx" ON "company_info_rels" USING btree ("path");
CREATE INDEX "company_info_rels_services_id_idx" ON "company_info_rels" USING btree ("services_id");
CREATE INDEX "company_info_rels_reviews_id_idx" ON "company_info_rels" USING btree ("reviews_id");
