/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    authors: Author;
    'blog-posts': BlogPost;
    'case-studies': CaseStudy;
    tags: Tag;
    services: Service;
    reviews: Review;
    pages: Page;
    faqs: Faq;
    'team-members': TeamMember;
    categories: Category;
    forms: Form;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'company-info': CompanyInfo;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'company-info': CompanyInfoSelect<false> | CompanyInfoSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  bio?: string | null;
  email?: string | null;
  avatar?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug?: string | null;
  status: 'draft' | 'published';
  publishedAt?: string | null;
  author?: (number | null) | Author;
  category: number | Category;
  /**
   * Select tags or start typing to search/create new ones
   */
  tags?: (number | Tag)[] | null;
  /**
   * Enable to display this post prominently on the homepage or featured sections
   */
  featured?: boolean | null;
  featuredImage?: (number | null) | Media;
  /**
   * Brief summary for blog listing pages
   */
  summary?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage categories for Blog Posts and Case Studies
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Display name for the category
   */
  name: string;
  /**
   * URL-friendly identifier (auto-generated from name if left empty)
   */
  slug: string;
  /**
   * Select which content types this category applies to. A category can apply to multiple content types.
   */
  appliesTo: ('blogs' | 'case-studies')[];
  /**
   * Optional description for this category
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage tags for Blog Posts and Case Studies
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  /**
   * The display name of the tag (e.g., 'Water Heater', 'DIY')
   */
  name: string;
  /**
   * URL-friendly identifier (auto-generated from name if left empty)
   */
  slug: string;
  /**
   * Select which content types this tag applies to. A tag can apply to multiple content types.
   */
  appliesTo: ('blogs' | 'case-studies')[];
  /**
   * Optional description for this tag
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  slug?: string | null;
  completedAt?: string | null;
  /**
   * Check this box to highlight this case study on the homepage
   */
  featured?: boolean | null;
  client?: string | null;
  location?: string | null;
  /**
   * e.g. '$950'
   */
  budget?: string | null;
  /**
   * e.g. '2 Hours'
   */
  duration?: string | null;
  /**
   * Select the primary service related to this case study
   */
  relatedService?: (number | null) | Service;
  /**
   * Select tags for this case study to help with filtering and organization
   */
  tags?: (number | Tag)[] | null;
  review?: (number | null) | Review;
  category?: (number | null) | Category;
  /**
   * Brief summary for case study listing pages
   */
  summary?: string | null;
  featuredImage?: (number | null) | Media;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  hero: {
    type: 'default' | 'highImpact' | 'servicesHero' | 'minimal' | 'none';
    title?: string | null;
    /**
     * Text to highlight in primary color (case-insensitive)
     */
    titleHighlight?: string | null;
    description?: string | null;
    floatingText?: string | null;
    badge?: {
      content: string;
      variant?: ('default' | 'secondary' | 'destructive' | 'outline') | null;
      size?: ('sm' | 'default' | 'lg') | null;
      icon?: string | null;
    };
    bgImage?: (number | null) | Media;
    fgImage?: (number | null) | Media;
    heroTheme?: ('muted' | 'primary-gradient') | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom' | 'email' | 'phone' | 'badge') | null;
            label: string;
            url?: string | null;
            newTab?: boolean | null;
            email?: string | null;
            phoneNumber?: string | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'services';
                  value: number | Service;
                } | null);
            style?:
              | (
                  | 'primary'
                  | 'secondary'
                  | 'outline'
                  | 'ghost'
                  | 'destructive'
                  | 'badge'
                  | 'badge-pulsing'
                  | 'primary-gradient-dots'
                )
              | null;
          };
          id?: string | null;
        }[]
      | null;
    /**
     * Add up to 4 trust indicators (icons with text)
     */
    trustIndicators?:
      | {
          icon: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    showDate?: boolean | null;
  };
  title: string;
  slug: string;
  description: string;
  longDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  icon: string;
  image: number | Media;
  isEmergency?: boolean | null;
  availability?: string | null;
  /**
   * Select services that belong to this category. The selected services will automatically have their 'Parent Service' field updated to point to this service.
   */
  subServices?: (number | Service)[] | null;
  parentService?: (number | null) | Service;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  /**
   * The 'Last updated' date shown on the page
   */
  lastUpdated?: string | null;
  status: 'draft' | 'published';
  layout: (
    | {
        background?: {
          bg?: ('transparent' | 'muted' | 'primary') | null;
          decoration?: ('none' | 'dots') | null;
        };
        content: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        paddingTopOption?: ('none' | 'small' | 'default' | 'big') | null;
        paddingBottomOption?: ('none' | 'small' | 'default' | 'big') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'legalContent';
      }
    | {
        background?: {
          bg?: ('transparent' | 'muted' | 'primary') | null;
          decoration?: ('none' | 'dots') | null;
        };
        title?: string | null;
        description?: string | null;
        /**
         * Leave blank to use email from Company Info global
         */
        email?: string | null;
        /**
         * Leave blank to use phone from Company Info global
         */
        phone?: string | null;
        /**
         * Leave blank to use address from Company Info global
         */
        address?: string | null;
        paddingTopOption?: ('none' | 'small' | 'default' | 'big') | null;
        paddingBottomOption?: ('none' | 'small' | 'default' | 'big') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'legalContact';
      }
    | {
        background?: {
          bg?: ('transparent' | 'muted' | 'primary') | null;
          decoration?: ('none' | 'dots') | null;
        };
        label?: string | null;
        href?: string | null;
        centered?: boolean | null;
        paddingTopOption?: ('none' | 'small' | 'default' | 'big') | null;
        paddingBottomOption?: ('none' | 'small' | 'default' | 'big') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'backLink';
      }
    | {
        title?: string | null;
        /**
         * Text to highlight in primary color (case-insensitive)
         */
        titleHighlight?: string | null;
        background?: {
          bg?: ('transparent' | 'muted' | 'primary') | null;
          decoration?: ('none' | 'dots') | null;
        };
        description?: string | null;
        faqs?: (number | Faq)[] | null;
        cta: {
          showCta?: boolean | null;
          headline?: string | null;
          text?: string | null;
          ctaLink: {
            type?: ('reference' | 'custom' | 'email' | 'phone' | 'badge') | null;
            label: string;
            url?: string | null;
            newTab?: boolean | null;
            email?: string | null;
            phoneNumber?: string | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'services';
                  value: number | Service;
                } | null);
            style?:
              | (
                  | 'primary'
                  | 'secondary'
                  | 'outline'
                  | 'ghost'
                  | 'destructive'
                  | 'badge'
                  | 'badge-pulsing'
                  | 'primary-gradient-dots'
                )
              | null;
          };
        };
        paddingTopOption?: ('none' | 'small' | 'default' | 'big') | null;
        paddingBottomOption?: ('none' | 'small' | 'default' | 'big') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'faq';
      }
    | ReviewBlock
    | {
        background?: {
          bg?: ('transparent' | 'muted' | 'primary') | null;
          decoration?: ('none' | 'dots') | null;
        };
        subtitle?: string | null;
        title?: string | null;
        /**
         * Text to highlight in primary color
         */
        titleHighlight?: string | null;
        description?: string | null;
        certifications?:
          | {
              name: string;
              description?: string | null;
              icon?: string | null;
              id?: string | null;
            }[]
          | null;
        paddingTopOption?: ('none' | 'small' | 'default' | 'big') | null;
        paddingBottomOption?: ('none' | 'small' | 'default' | 'big') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'certifications';
      }
    | {
        background?: {
          bg?: ('transparent' | 'muted' | 'primary') | null;
          decoration?: ('none' | 'dots') | null;
        };
        title?: string | null;
        /**
         * Text to highlight in the title (e.g. 'Water City Plumbing Experts')
         */
        titleHighlight?: string | null;
        description?: string | null;
        selectedMembers: (number | TeamMember)[];
        paddingTopOption?: ('none' | 'small' | 'default' | 'big') | null;
        paddingBottomOption?: ('none' | 'small' | 'default' | 'big') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'team';
      }
    | {
        background?: {
          bg?: ('transparent' | 'muted' | 'primary') | null;
          decoration?: ('none' | 'dots') | null;
        };
        /**
         * The full main heading
         */
        title: string;
        /**
         * Text to highlight (must match exactly)
         */
        titleHighlight?: string | null;
        /**
         * Optional tagline like 'BY THE NUMBERS'
         */
        bottomText?: string | null;
        cols?: ('3' | '4' | '6') | null;
        backgroundColor?: ('transparent' | 'muted') | null;
        stats?:
          | {
              /**
               * e.g., '500+' or '99%'
               */
              value: string;
              /**
               * e.g., 'Projects Completed'
               */
              label: string;
              id?: string | null;
            }[]
          | null;
        paddingTopOption?: ('none' | 'small' | 'default' | 'big') | null;
        paddingBottomOption?: ('none' | 'small' | 'default' | 'big') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'trustStats';
      }
    | TimelineBlock
    | {
        background?: {
          bg?: ('transparent' | 'muted' | 'primary') | null;
          decoration?: ('none' | 'dots') | null;
        };
        contentType: 'blogs' | 'case-studies' | 'services';
        limit?: number | null;
        itemsPerRow?: ('1' | '2' | '3' | '4') | null;
        sortBy?: ('newest' | 'oldest' | 'titleAsc' | 'titleDesc') | null;
        /**
         * Only display items marked as featured
         */
        featuredOnly?: boolean | null;
        /**
         * Allow visitors to filter content by category, search, etc.
         */
        showFilters?: boolean | null;
        /**
         * Show a search input to filter by text
         */
        showSearch?: boolean | null;
        paginationStyle?: ('none' | 'numbered' | 'loadMore' | 'infiniteScroll') | null;
        paddingTopOption?: ('none' | 'small' | 'default' | 'big') | null;
        paddingBottomOption?: ('none' | 'small' | 'default' | 'big') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contentFetcher';
      }
    | {
        background?: {
          bg?: ('transparent' | 'muted' | 'primary') | null;
          decoration?: ('none' | 'dots') | null;
        };
        /**
         * Small tag text displayed above the main title
         */
        tagTitle?: string | null;
        mainTitle: string;
        /**
         * Text segment from the Main Title to highlight in primary color (case-sensitive)
         */
        highlightedText?: string | null;
        description?: string | null;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom' | 'email' | 'phone' | 'badge') | null;
                label: string;
                url?: string | null;
                newTab?: boolean | null;
                email?: string | null;
                phoneNumber?: string | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: number | Page;
                    } | null)
                  | ({
                      relationTo: 'services';
                      value: number | Service;
                    } | null);
                style?:
                  | (
                      | 'primary'
                      | 'secondary'
                      | 'outline'
                      | 'ghost'
                      | 'destructive'
                      | 'badge'
                      | 'badge-pulsing'
                      | 'primary-gradient-dots'
                    )
                  | null;
              };
              id?: string | null;
            }[]
          | null;
        textAlign?: ('left' | 'center' | 'right') | null;
        buttonsAlign?: ('left' | 'center' | 'right') | null;
        paddingTopOption?: ('none' | 'small' | 'default' | 'big') | null;
        paddingBottomOption?: ('none' | 'small' | 'default' | 'big') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'titleContent';
      }
    | {
        background?: {
          bg?: ('transparent' | 'muted' | 'primary') | null;
          decoration?: ('none' | 'dots') | null;
        };
        textAlign?: ('left' | 'center' | 'right') | null;
        columns?: ('1' | '2' | '3' | '4' | '5' | '6') | null;
        paddingTopOption?: ('none' | 'small' | 'default' | 'big') | null;
        paddingBottomOption?: ('none' | 'small' | 'default' | 'big') | null;
        items?:
          | {
              image: number | Media;
              title: string;
              link?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'imagesGrid';
      }
    | {
        background?: {
          bg?: ('transparent' | 'muted' | 'primary') | null;
          decoration?: ('none' | 'dots') | null;
        };
        columns?: ('1' | '2' | '3' | '4' | '5' | '6') | null;
        cardLayout?: ('stacked' | 'sideBySide') | null;
        /**
         * If enabled, cards will show a shadow and primary color border on hover, and icons will turn primary color.
         */
        enableHighlight?: boolean | null;
        paddingTopOption?: ('none' | 'small' | 'default' | 'big') | null;
        paddingBottomOption?: ('none' | 'small' | 'default' | 'big') | null;
        cards?:
          | {
              icon?: string | null;
              title: string;
              description?: string | null;
              link?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'cardsGrid';
      }
    | {
        background?: {
          bg?: ('transparent' | 'muted' | 'primary') | null;
          decoration?: ('none' | 'dots') | null;
        };
        title?: string | null;
        headline?: string | null;
        /**
         * Text to be highlighted with primary color within the headline (if applicable)
         */
        highlightedHeadlineText?: string | null;
        description?: string | null;
        useGlobalServiceAreas?: boolean | null;
        paddingTopOption?: ('none' | 'small' | 'default' | 'big') | null;
        paddingBottomOption?: ('none' | 'small' | 'default' | 'big') | null;
        customServiceAreas?:
          | {
              name: string;
              id?: string | null;
            }[]
          | null;
        /**
         * Text displayed below the service areas grid.
         */
        bottomText?: string | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'serviceAreasBlock';
      }
    | {
        background?: {
          bg?: ('transparent' | 'muted' | 'primary') | null;
          decoration?: ('none' | 'dots') | null;
        };
        tag?: string | null;
        title: string;
        /**
         * Text to highlight within the Title. Case-sensitive.
         */
        highlightedText?: string | null;
        description?: string | null;
        /**
         * Select a service to highlight as the emergency service (e.g. 24/7). This will appear first.
         */
        emergencyService?: (number | null) | Service;
        selectedServices: (number | Service)[];
        layout?: ('grid' | 'carousel') | null;
        cta: {
          type?: ('reference' | 'custom' | 'email' | 'phone' | 'badge') | null;
          label: string;
          url?: string | null;
          newTab?: boolean | null;
          email?: string | null;
          phoneNumber?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null);
          style?:
            | (
                | 'primary'
                | 'secondary'
                | 'outline'
                | 'ghost'
                | 'destructive'
                | 'badge'
                | 'badge-pulsing'
                | 'primary-gradient-dots'
              )
            | null;
        };
        /**
         * Legacy option. Prefer using the Call to Action field above.
         */
        linkToAllServices?: boolean | null;
        paddingTopOption?: ('none' | 'small' | 'default' | 'big') | null;
        paddingBottomOption?: ('none' | 'small' | 'default' | 'big') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'highlightedServices';
      }
    | {
        background?: {
          bg?: ('transparent' | 'muted' | 'primary') | null;
          decoration?: ('none' | 'dots') | null;
        };
        textAlign?: ('left' | 'center' | 'right') | null;
        textColor?: ('regular' | 'primary') | null;
        paddingTopOption?: ('none' | 'small' | 'default' | 'big') | null;
        paddingBottomOption?: ('none' | 'small' | 'default' | 'big') | null;
        columns?: ('1' | '2' | '3' | '4' | '5' | '6') | null;
        /**
         * Show vertical and horizontal separators between items.
         */
        showSeparators?: boolean | null;
        numberItems?:
          | {
              title: string;
              subTitle?: string | null;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'numbers';
      }
    | {
        background?: {
          bg?: ('transparent' | 'muted' | 'primary') | null;
          decoration?: ('none' | 'dots') | null;
        };
        columns?:
          | {
              type?: ('content' | 'image') | null;
              image?: (number | null) | Media;
              richText?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              links?:
                | {
                    link: {
                      type?: ('reference' | 'custom' | 'email' | 'phone' | 'badge') | null;
                      label: string;
                      url?: string | null;
                      newTab?: boolean | null;
                      email?: string | null;
                      phoneNumber?: string | null;
                      reference?:
                        | ({
                            relationTo: 'pages';
                            value: number | Page;
                          } | null)
                        | ({
                            relationTo: 'services';
                            value: number | Service;
                          } | null);
                      style?:
                        | (
                            | 'primary'
                            | 'secondary'
                            | 'outline'
                            | 'ghost'
                            | 'destructive'
                            | 'badge'
                            | 'badge-pulsing'
                            | 'primary-gradient-dots'
                          )
                        | null;
                    };
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        paddingTopOption?: ('none' | 'small' | 'default' | 'big') | null;
        paddingBottomOption?: ('none' | 'small' | 'default' | 'big') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'dualColumn';
      }
    | {
        background?: {
          bg?: ('transparent' | 'muted' | 'primary') | null;
          decoration?: ('none' | 'dots') | null;
        };
        form: number | Form;
        enableIntro?: boolean | null;
        introContent?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableHeader?: boolean | null;
        headerContent?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableFooter?: boolean | null;
        footerContent?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableBorder?: boolean | null;
        paddingTopOption?: ('none' | 'small' | 'default' | 'big') | null;
        paddingBottomOption?: ('none' | 'small' | 'default' | 'big') | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'formBlock';
      }
  )[];
  hero: {
    type: 'default' | 'highImpact' | 'servicesHero' | 'minimal' | 'none';
    title?: string | null;
    /**
     * Text to highlight in primary color (case-insensitive)
     */
    titleHighlight?: string | null;
    description?: string | null;
    floatingText?: string | null;
    badge?: {
      content: string;
      variant?: ('default' | 'secondary' | 'destructive' | 'outline') | null;
      size?: ('sm' | 'default' | 'lg') | null;
      icon?: string | null;
    };
    bgImage?: (number | null) | Media;
    fgImage?: (number | null) | Media;
    heroTheme?: ('muted' | 'primary-gradient') | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom' | 'email' | 'phone' | 'badge') | null;
            label: string;
            url?: string | null;
            newTab?: boolean | null;
            email?: string | null;
            phoneNumber?: string | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'services';
                  value: number | Service;
                } | null);
            style?:
              | (
                  | 'primary'
                  | 'secondary'
                  | 'outline'
                  | 'ghost'
                  | 'destructive'
                  | 'badge'
                  | 'badge-pulsing'
                  | 'primary-gradient-dots'
                )
              | null;
          };
          id?: string | null;
        }[]
      | null;
    /**
     * Add up to 4 trust indicators (icons with text)
     */
    trustIndicators?:
      | {
          icon: string;
          title: string;
          description: string;
          id?: string | null;
        }[]
      | null;
    showDate?: boolean | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  question: string;
  answer: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReviewBlock".
 */
export interface ReviewBlock {
  background?: {
    bg?: ('transparent' | 'muted' | 'primary') | null;
    decoration?: ('none' | 'dots') | null;
  };
  title?: string | null;
  subtitle?: string | null;
  /**
   * Choose 'Manual' to add one-off reviews for this page only, or 'From Collection' to select shared reviews from the main Reviews list.
   */
  source?: ('manual' | 'collection') | null;
  manualReviews?:
    | {
        author: string;
        rating?: number | null;
        content: string;
        date?: string | null;
        id?: string | null;
      }[]
    | null;
  selectedReviews?: (number | Review)[] | null;
  paddingTopOption?: ('none' | 'small' | 'default' | 'big') | null;
  paddingBottomOption?: ('none' | 'small' | 'default' | 'big') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'reviewsSection';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  author: string;
  rating: number;
  date: string;
  platform: 'google' | 'facebook' | 'yelp' | 'website' | 'other';
  avatar?: (number | null) | Media;
  content: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  role: string;
  bio?: string | null;
  image: number | Media;
  certifications?:
    | {
        certification: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock".
 */
export interface TimelineBlock {
  background?: {
    bg?: ('transparent' | 'muted' | 'primary') | null;
    decoration?: ('none' | 'dots') | null;
  };
  /**
   * The main heading for the timeline section
   */
  title: string;
  items?:
    | {
        /**
         * The main heading for this timeline entry
         */
        title: string;
        /**
         * When this event occurred
         */
        date: string;
        /**
         * Detailed information about this timeline entry
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  paddingTopOption?: ('none' | 'small' | 'default' | 'big') | null;
  paddingBottomOption?: ('none' | 'small' | 'default' | 'big') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'timeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: number;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            placeholder?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            placeholder?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            placeholder?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            placeholder?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
        | {
            background?: {
              bg?: ('transparent' | 'muted' | 'primary') | null;
              decoration?: ('none' | 'dots') | null;
            };
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'urgency';
          }
        | {
            background?: {
              bg?: ('transparent' | 'muted' | 'primary') | null;
              decoration?: ('none' | 'dots') | null;
            };
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'propertyType';
          }
        | {
            background?: {
              bg?: ('transparent' | 'muted' | 'primary') | null;
              decoration?: ('none' | 'dots') | null;
            };
            name: string;
            label: string;
            width?: number | null;
            required?: boolean | null;
            allowedFileTypes?: ('all' | 'image/*' | 'application/pdf' | 'image/*,application/pdf') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'file';
          }
        | {
            background?: {
              bg?: ('transparent' | 'muted' | 'primary') | null;
              decoration?: ('none' | 'dots') | null;
            };
            name: string;
            label?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkboxGroup';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: number | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'forms';
        value: number | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  bio?: T;
  email?: T;
  avatar?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  publishedAt?: T;
  author?: T;
  category?: T;
  tags?: T;
  featured?: T;
  featuredImage?: T;
  summary?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  completedAt?: T;
  featured?: T;
  client?: T;
  location?: T;
  budget?: T;
  duration?: T;
  relatedService?: T;
  tags?: T;
  review?: T;
  category?: T;
  summary?: T;
  featuredImage?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  appliesTo?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        type?: T;
        title?: T;
        titleHighlight?: T;
        description?: T;
        floatingText?: T;
        badge?:
          | T
          | {
              content?: T;
              variant?: T;
              size?: T;
              icon?: T;
            };
        bgImage?: T;
        fgImage?: T;
        heroTheme?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    label?: T;
                    url?: T;
                    newTab?: T;
                    email?: T;
                    phoneNumber?: T;
                    reference?: T;
                    style?: T;
                  };
              id?: T;
            };
        trustIndicators?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        showDate?: T;
      };
  title?: T;
  slug?: T;
  description?: T;
  longDescription?: T;
  icon?: T;
  image?: T;
  isEmergency?: T;
  availability?: T;
  subServices?: T;
  parentService?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  author?: T;
  rating?: T;
  date?: T;
  platform?: T;
  avatar?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  lastUpdated?: T;
  status?: T;
  layout?:
    | T
    | {
        legalContent?:
          | T
          | {
              background?:
                | T
                | {
                    bg?: T;
                    decoration?: T;
                  };
              content?: T;
              paddingTopOption?: T;
              paddingBottomOption?: T;
              id?: T;
              blockName?: T;
            };
        legalContact?:
          | T
          | {
              background?:
                | T
                | {
                    bg?: T;
                    decoration?: T;
                  };
              title?: T;
              description?: T;
              email?: T;
              phone?: T;
              address?: T;
              paddingTopOption?: T;
              paddingBottomOption?: T;
              id?: T;
              blockName?: T;
            };
        backLink?:
          | T
          | {
              background?:
                | T
                | {
                    bg?: T;
                    decoration?: T;
                  };
              label?: T;
              href?: T;
              centered?: T;
              paddingTopOption?: T;
              paddingBottomOption?: T;
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              title?: T;
              titleHighlight?: T;
              background?:
                | T
                | {
                    bg?: T;
                    decoration?: T;
                  };
              description?: T;
              faqs?: T;
              cta?:
                | T
                | {
                    showCta?: T;
                    headline?: T;
                    text?: T;
                    ctaLink?:
                      | T
                      | {
                          type?: T;
                          label?: T;
                          url?: T;
                          newTab?: T;
                          email?: T;
                          phoneNumber?: T;
                          reference?: T;
                          style?: T;
                        };
                  };
              paddingTopOption?: T;
              paddingBottomOption?: T;
              id?: T;
              blockName?: T;
            };
        reviewsSection?: T | ReviewBlockSelect<T>;
        certifications?:
          | T
          | {
              background?:
                | T
                | {
                    bg?: T;
                    decoration?: T;
                  };
              subtitle?: T;
              title?: T;
              titleHighlight?: T;
              description?: T;
              certifications?:
                | T
                | {
                    name?: T;
                    description?: T;
                    icon?: T;
                    id?: T;
                  };
              paddingTopOption?: T;
              paddingBottomOption?: T;
              id?: T;
              blockName?: T;
            };
        team?:
          | T
          | {
              background?:
                | T
                | {
                    bg?: T;
                    decoration?: T;
                  };
              title?: T;
              titleHighlight?: T;
              description?: T;
              selectedMembers?: T;
              paddingTopOption?: T;
              paddingBottomOption?: T;
              id?: T;
              blockName?: T;
            };
        trustStats?:
          | T
          | {
              background?:
                | T
                | {
                    bg?: T;
                    decoration?: T;
                  };
              title?: T;
              titleHighlight?: T;
              bottomText?: T;
              cols?: T;
              backgroundColor?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    id?: T;
                  };
              paddingTopOption?: T;
              paddingBottomOption?: T;
              id?: T;
              blockName?: T;
            };
        timeline?: T | TimelineBlockSelect<T>;
        contentFetcher?:
          | T
          | {
              background?:
                | T
                | {
                    bg?: T;
                    decoration?: T;
                  };
              contentType?: T;
              limit?: T;
              itemsPerRow?: T;
              sortBy?: T;
              featuredOnly?: T;
              showFilters?: T;
              showSearch?: T;
              paginationStyle?: T;
              paddingTopOption?: T;
              paddingBottomOption?: T;
              id?: T;
              blockName?: T;
            };
        titleContent?:
          | T
          | {
              background?:
                | T
                | {
                    bg?: T;
                    decoration?: T;
                  };
              tagTitle?: T;
              mainTitle?: T;
              highlightedText?: T;
              description?: T;
              links?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          label?: T;
                          url?: T;
                          newTab?: T;
                          email?: T;
                          phoneNumber?: T;
                          reference?: T;
                          style?: T;
                        };
                    id?: T;
                  };
              textAlign?: T;
              buttonsAlign?: T;
              paddingTopOption?: T;
              paddingBottomOption?: T;
              id?: T;
              blockName?: T;
            };
        imagesGrid?:
          | T
          | {
              background?:
                | T
                | {
                    bg?: T;
                    decoration?: T;
                  };
              textAlign?: T;
              columns?: T;
              paddingTopOption?: T;
              paddingBottomOption?: T;
              items?:
                | T
                | {
                    image?: T;
                    title?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cardsGrid?:
          | T
          | {
              background?:
                | T
                | {
                    bg?: T;
                    decoration?: T;
                  };
              columns?: T;
              cardLayout?: T;
              enableHighlight?: T;
              paddingTopOption?: T;
              paddingBottomOption?: T;
              cards?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    link?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        serviceAreasBlock?:
          | T
          | {
              background?:
                | T
                | {
                    bg?: T;
                    decoration?: T;
                  };
              title?: T;
              headline?: T;
              highlightedHeadlineText?: T;
              description?: T;
              useGlobalServiceAreas?: T;
              paddingTopOption?: T;
              paddingBottomOption?: T;
              customServiceAreas?:
                | T
                | {
                    name?: T;
                    id?: T;
                  };
              bottomText?: T;
              id?: T;
              blockName?: T;
            };
        highlightedServices?:
          | T
          | {
              background?:
                | T
                | {
                    bg?: T;
                    decoration?: T;
                  };
              tag?: T;
              title?: T;
              highlightedText?: T;
              description?: T;
              emergencyService?: T;
              selectedServices?: T;
              layout?: T;
              cta?:
                | T
                | {
                    type?: T;
                    label?: T;
                    url?: T;
                    newTab?: T;
                    email?: T;
                    phoneNumber?: T;
                    reference?: T;
                    style?: T;
                  };
              linkToAllServices?: T;
              paddingTopOption?: T;
              paddingBottomOption?: T;
              id?: T;
              blockName?: T;
            };
        numbers?:
          | T
          | {
              background?:
                | T
                | {
                    bg?: T;
                    decoration?: T;
                  };
              textAlign?: T;
              textColor?: T;
              paddingTopOption?: T;
              paddingBottomOption?: T;
              columns?: T;
              showSeparators?: T;
              numberItems?:
                | T
                | {
                    title?: T;
                    subTitle?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        dualColumn?:
          | T
          | {
              background?:
                | T
                | {
                    bg?: T;
                    decoration?: T;
                  };
              columns?:
                | T
                | {
                    type?: T;
                    image?: T;
                    richText?: T;
                    links?:
                      | T
                      | {
                          link?:
                            | T
                            | {
                                type?: T;
                                label?: T;
                                url?: T;
                                newTab?: T;
                                email?: T;
                                phoneNumber?: T;
                                reference?: T;
                                style?: T;
                              };
                          id?: T;
                        };
                    id?: T;
                  };
              paddingTopOption?: T;
              paddingBottomOption?: T;
              id?: T;
              blockName?: T;
            };
        formBlock?:
          | T
          | {
              background?:
                | T
                | {
                    bg?: T;
                    decoration?: T;
                  };
              form?: T;
              enableIntro?: T;
              introContent?: T;
              enableHeader?: T;
              headerContent?: T;
              enableFooter?: T;
              footerContent?: T;
              enableBorder?: T;
              paddingTopOption?: T;
              paddingBottomOption?: T;
              id?: T;
              blockName?: T;
            };
      };
  hero?:
    | T
    | {
        type?: T;
        title?: T;
        titleHighlight?: T;
        description?: T;
        floatingText?: T;
        badge?:
          | T
          | {
              content?: T;
              variant?: T;
              size?: T;
              icon?: T;
            };
        bgImage?: T;
        fgImage?: T;
        heroTheme?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    label?: T;
                    url?: T;
                    newTab?: T;
                    email?: T;
                    phoneNumber?: T;
                    reference?: T;
                    style?: T;
                  };
              id?: T;
            };
        trustIndicators?:
          | T
          | {
              icon?: T;
              title?: T;
              description?: T;
              id?: T;
            };
        showDate?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ReviewBlock_select".
 */
export interface ReviewBlockSelect<T extends boolean = true> {
  background?:
    | T
    | {
        bg?: T;
        decoration?: T;
      };
  title?: T;
  subtitle?: T;
  source?: T;
  manualReviews?:
    | T
    | {
        author?: T;
        rating?: T;
        content?: T;
        date?: T;
        id?: T;
      };
  selectedReviews?: T;
  paddingTopOption?: T;
  paddingBottomOption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TimelineBlock_select".
 */
export interface TimelineBlockSelect<T extends boolean = true> {
  background?:
    | T
    | {
        bg?: T;
        decoration?: T;
      };
  title?: T;
  items?:
    | T
    | {
        title?: T;
        date?: T;
        description?: T;
        id?: T;
      };
  paddingTopOption?: T;
  paddingBottomOption?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  bio?: T;
  image?: T;
  certifications?:
    | T
    | {
        certification?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  appliesTo?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              placeholder?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              placeholder?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              placeholder?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              placeholder?: T;
              id?: T;
              blockName?: T;
            };
        urgency?:
          | T
          | {
              background?:
                | T
                | {
                    bg?: T;
                    decoration?: T;
                  };
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        propertyType?:
          | T
          | {
              background?:
                | T
                | {
                    bg?: T;
                    decoration?: T;
                  };
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        file?:
          | T
          | {
              background?:
                | T
                | {
                    bg?: T;
                    decoration?: T;
                  };
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              allowedFileTypes?: T;
              id?: T;
              blockName?: T;
            };
        checkboxGroup?:
          | T
          | {
              background?:
                | T
                | {
                    bg?: T;
                    decoration?: T;
                  };
              name?: T;
              label?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems: {
    link: {
      type?: ('reference' | 'custom' | 'email' | 'phone' | 'badge') | null;
      label: string;
      url?: string | null;
      newTab?: boolean | null;
      email?: string | null;
      phoneNumber?: string | null;
      reference?:
        | ({
            relationTo: 'pages';
            value: number | Page;
          } | null)
        | ({
            relationTo: 'services';
            value: number | Service;
          } | null);
      style?:
        | (
            | 'primary'
            | 'secondary'
            | 'outline'
            | 'ghost'
            | 'destructive'
            | 'badge'
            | 'badge-pulsing'
            | 'primary-gradient-dots'
          )
        | null;
    };
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  cta: {
    headline: string;
    subheadline: string;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom' | 'email' | 'phone' | 'badge') | null;
            label: string;
            url?: string | null;
            newTab?: boolean | null;
            email?: string | null;
            phoneNumber?: string | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: number | Page;
                } | null)
              | ({
                  relationTo: 'services';
                  value: number | Service;
                } | null);
            style?:
              | (
                  | 'primary'
                  | 'secondary'
                  | 'outline'
                  | 'ghost'
                  | 'destructive'
                  | 'badge'
                  | 'badge-pulsing'
                  | 'primary-gradient-dots'
                )
              | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  navLinks?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'email' | 'phone' | 'badge') | null;
          label: string;
          url?: string | null;
          newTab?: boolean | null;
          email?: string | null;
          phoneNumber?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null);
          style?:
            | (
                | 'primary'
                | 'secondary'
                | 'outline'
                | 'ghost'
                | 'destructive'
                | 'badge'
                | 'badge-pulsing'
                | 'primary-gradient-dots'
              )
            | null;
        };
        id?: string | null;
      }[]
    | null;
  /**
   * Use {year} to insert current year and {brand} for brand name
   */
  copyrightText?: string | null;
  bottomLinks?:
    | {
        link: {
          type?: ('reference' | 'custom' | 'email' | 'phone' | 'badge') | null;
          label: string;
          url?: string | null;
          newTab?: boolean | null;
          email?: string | null;
          phoneNumber?: string | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: number | Page;
              } | null)
            | ({
                relationTo: 'services';
                value: number | Service;
              } | null);
          style?:
            | (
                | 'primary'
                | 'secondary'
                | 'outline'
                | 'ghost'
                | 'destructive'
                | 'badge'
                | 'badge-pulsing'
                | 'primary-gradient-dots'
              )
            | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-info".
 */
export interface CompanyInfo {
  id: number;
  brand: {
    name: string;
    description: string;
    logo: number | Media;
  };
  phone: string;
  email: string;
  address: string;
  /**
   * Links to your social media profiles
   */
  socials?:
    | {
        platform: 'facebook' | 'instagram' | 'linkedin' | 'twitter' | 'youtube';
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Your weekly business operating hours
   */
  workingHours?:
    | {
        day: string;
        time: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Manage overarching business details, location settings, service priorities, and review aggregations for optimizing search engine visibility.
   */
  seo: {
    businessType: 'Plumber' | 'LocalBusiness' | 'HomeAndConstructionBusiness';
    foundingDate?: string | null;
    /**
     * The primary phone number displayed for SEO and services.
     */
    phoneDisplay: string;
    location: {
      streetAddress: string;
      city: string;
      state: string;
      stateCode: string;
      postalCode: string;
      country: string;
      countryCode: string;
      latitude: string;
      longitude: string;
    };
    /**
     * Services to highlight in Schema.org markup
     */
    priorityServices?: (number | Service)[] | null;
    /**
     * Service designated as the 24/7 emergency offering
     */
    emergencyService?: (number | null) | Service;
    serviceAreas?:
      | {
          name: string;
          type: 'Suburb' | 'City' | 'Region';
          id?: string | null;
        }[]
      | null;
    /**
     * Choose how reviews are sourced and displayed on the website. Select 'Google Places API' to automatically fetch reviews or 'Manual Input' to manually enter rating data and select highlighted reviews.
     */
    reviews: {
      source: 'hardcoded' | 'google-api';
      ratingValue: number;
      reviewCount: number;
      bestRating?: number | null;
      worstRating?: number | null;
      /**
       * Select reviews from the Reviews collection to highlight on the website.
       */
      highlightedReviews?:
        | {
            relationTo: 'reviews';
            value: number | Review;
          }[]
        | null;
      mapsUrl?: string | null;
      placeId?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              label?: T;
              url?: T;
              newTab?: T;
              email?: T;
              phoneNumber?: T;
              reference?: T;
              style?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  cta?:
    | T
    | {
        headline?: T;
        subheadline?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    label?: T;
                    url?: T;
                    newTab?: T;
                    email?: T;
                    phoneNumber?: T;
                    reference?: T;
                    style?: T;
                  };
              id?: T;
            };
      };
  navLinks?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              label?: T;
              url?: T;
              newTab?: T;
              email?: T;
              phoneNumber?: T;
              reference?: T;
              style?: T;
            };
        id?: T;
      };
  copyrightText?: T;
  bottomLinks?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              label?: T;
              url?: T;
              newTab?: T;
              email?: T;
              phoneNumber?: T;
              reference?: T;
              style?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-info_select".
 */
export interface CompanyInfoSelect<T extends boolean = true> {
  brand?:
    | T
    | {
        name?: T;
        description?: T;
        logo?: T;
      };
  phone?: T;
  email?: T;
  address?: T;
  socials?:
    | T
    | {
        platform?: T;
        label?: T;
        href?: T;
        id?: T;
      };
  workingHours?:
    | T
    | {
        day?: T;
        time?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        businessType?: T;
        foundingDate?: T;
        phoneDisplay?: T;
        location?:
          | T
          | {
              streetAddress?: T;
              city?: T;
              state?: T;
              stateCode?: T;
              postalCode?: T;
              country?: T;
              countryCode?: T;
              latitude?: T;
              longitude?: T;
            };
        priorityServices?: T;
        emergencyService?: T;
        serviceAreas?:
          | T
          | {
              name?: T;
              type?: T;
              id?: T;
            };
        reviews?:
          | T
          | {
              source?: T;
              ratingValue?: T;
              reviewCount?: T;
              bestRating?: T;
              worstRating?: T;
              highlightedReviews?: T;
              mapsUrl?: T;
              placeId?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepTimelineBlock".
 */
export interface StepTimelineBlock {
  background?: {
    bg?: ('transparent' | 'muted' | 'primary') | null;
    decoration?: ('none' | 'dots') | null;
  };
  paddingTop?: boolean | null;
  paddingBottom?: boolean | null;
  items?:
    | {
        /**
         * Small label shown above the heading
         */
        label?: string | null;
        /**
         * The main heading for this item
         */
        heading: string;
        /**
         * Detailed information for this item
         */
        content?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stepTimeline';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}